# Generated by Django 4.2.7 on 2023-11-15 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_myuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='phone',
            field=models.CharField(max_length=12, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='otprequest',
            name='valid_until',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 11, 15, 11, 10, 35, 354460, tzinfo=datetime.timezone.utc)),
        ),
    ]
