# Generated by Django 4.2.7 on 2023-11-15 14:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import onlineshop.utils.db.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_otprequest_phone_alter_otprequest_valid_until'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='otprequest',
            name='valid_until',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 11, 15, 14, 39, 46, 484776, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.PositiveBigIntegerField(blank=True, error_messages={'unique': 'A user with this mobile number already exists.'}, null=True, unique=True, validators=[onlineshop.utils.db.validators.PhoneNumberValidator()], verbose_name='Phone Number')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
