# Generated by Django 4.2.7 on 2023-11-15 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_myuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='valid_until',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 11, 15, 14, 46, 5, 620391, tzinfo=datetime.timezone.utc)),
        ),
    ]
