# Generated by Django 4.2.7 on 2023-11-15 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_otprequest_valid_until'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='otprequest',
            name='valid_until',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 11, 15, 15, 24, 44, 133909, tzinfo=datetime.timezone.utc)),
        ),
    ]
