# Generated by Django 4.2.7 on 2023-11-25 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_otprequest_valid_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='valid_until',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 11, 25, 10, 45, 38, 22526, tzinfo=datetime.timezone.utc)),
        ),
    ]
