# Generated by Django 4.2.7 on 2023-11-25 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_otprequest_valid_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='valid_until',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 11, 25, 10, 47, 36, 815654, tzinfo=datetime.timezone.utc)),
        ),
    ]
