# Generated by Django 4.2.7 on 2023-12-07 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_otprequest_valid_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='valid_until',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 12, 7, 13, 12, 22, 497378, tzinfo=datetime.timezone.utc)),
        ),
    ]
